Repository maestrano/mnoe-admin-panel, pull requests merged in 2018-03, with the labels that each got.

#222 [MNOE-939] Added fix for correct product name to be used in provision process
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
Labels: bug

#221 [MNOE-146] Display teams
  src/app/components/mnoe-api/admin/teams.svc.coffee
  src/app/components/mnoe-teams-list/mnoe-teams-list.controller.coffee
  src/app/components/mnoe-teams-list/mnoe-teams-list.html
  src/app/components/mnoe-teams-list/mnoe-teams-list.less
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
  src/app/views/organization/organization.html
  src/locales/en-AU.json
Labels: enhancement

#223 [MNOE-887] Fix locale regression
  src/app/views/user/user.html
Labels: Status: Review Needed, bug

#225 [MNOE-950] Add tooltips with full names of products
  src/app/components/mno-product-selector/mno-product-selector.html
  src/app/views/organization/add-app-modal/add-app-modal.html
  src/app/views/organization/organization.html
  src/app/views/settings/apps/apps.html
Labels: enhancement

#212 [MNOE-908 ] Add Fields to Organization Info Page
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
  src/app/views/organization/organization.html
  src/locales/en-AU.json
Labels: enhancement

#220 [MNOE-872] Session timeout modal
  src/app/components/mno-session-timeout/mno-session-timeout.html
  src/app/components/mno-session-timeout/mno-session-timeout.svc.coffee
  src/app/index.config.coffee
  src/app/index.default-config.coffee
  src/locales/en-AU.json
Labels: enhancement

#206 [MNOE-890] Reseler's product on landing page
  src/app/views/settings/general/general.controller.coffee
Labels: Status: In Testing, enhancement

#219 [MNOE-921] Add role to user/org table
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.less
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.less
  src/app/services/user-roles-helper/user-roles-helper.coffee
  src/app/views/user/user.html
  src/locales/en-AU.json
Labels: enhancement
