Repository maestrano/mnoe-admin-panel, pull requests merged in 2018-04, with the labels that each got.

#234 [MNOE-920][MNOE-979] Implement marketplace view in admin panel
  src/app/components/mno-app-features/mno-app-features.coffee
  src/app/components/mno-app-features/mno-app-features.html
  src/app/components/mno-app-features/mno-app-features.less
  src/app/views/settings/apps/apps.controller.coffee
  src/app/views/settings/apps/apps.html
  src/app/views/settings/apps/modals/app-infos.coffee
  src/app/views/settings/apps/modals/app-infos.html
  src/app/views/settings/apps/modals/app-infos.less
  src/locales/en-AU.json
Labels: Status: In Testing, enhancement

#237 [MNOE-1017] Clarify Geo Fields
  src/app/views/user/user.html
  src/locales/en-AU.json
Labels: enhancement

#242 [MNOE-1031] Fix orgs table when no user
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
Labels: bug

#232 [OPAL-424] Added Provisioning events to subscription info page
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/order.html
  src/locales/en-AU.json
Labels: enhancement

#215 [MNOE-906] Improve Tables
  src/app/components/mnoe-orders-list/mnoe-orders-list.html
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
  src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
  src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.html
  src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
  src/app/components/mnoe-staffs-local-list/mnoe-staffs-local-list.html
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
  src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
  src/locales/en-AU.json
Labels: enhancement

#231 [MNOE-987] Tab Organization in Admin Panel Dashboard Sidebar
  src/app/views/dashboard.controller.coffee
  src/app/views/dashboard.layout.html
  src/locales/en-AU.json
Labels: enhancement

#236 [MNOE-1008] Price of product missing
  src/app/services/provisioning-helper/provisioning-helper.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
Labels: bug

#247 [MNOE-1028] Update subscription events upon updating subscriptions
  src/app/views/orders/order.controller.coffee
Labels: bug

#248 [MNOE-963] App Category selection
  src/app/components/mno-product-selector/mno-product-selector.controller.coffee
  src/app/components/mno-product-selector/mno-product-selector.html
  src/app/views/settings/apps/apps.controller.coffee
  src/app/views/settings/apps/apps.html
  src/app/views/settings/apps/apps.less
  src/locales/en-AU.json
Labels: enhancement

#238 [MNOE-971] Keep data when editing order
  src/app/components/mno-product-selector/mno-product-selector.controller.coffee
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/summary.controller.coffee
Labels: bug
