Repository maestrano/mnoe-admin-panel, pull requests merged in 2018-07, with the labels that each got.

#311 [MNOE-1229] Pricing Languages
  src/app/views/products/product.controller.coffee
Labels: bug

#278 [MNOE-1088] Quote Based Pricing
  src/app/components/mno-offers-list/mno-offers-list.coffee
  src/app/components/mno-offers-list/mno-offers-list.html
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/product-pricing-price.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en-AU.json
Labels: enhancement

#300 [MNOE-1110][OPAL-431] Custom data being copied over
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.html
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
  src/app/index.route.coffee
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/order.html
  src/app/views/organization/organization.controller.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/layout.controller.coffee
  src/app/views/provisioning/order.controller.coffee
  src/locales/en-AU.json
Labels: bug, enhancement

#316 [MNOE-1255] Invoice: Prevent negative values in tax rate
  src/app/views/invoices/invoice.html
Labels: bug

#318 [OPAL-513] Locales displayed on "Validate"
  src/app/views/provisioning/summary.controller.coffee
Labels: bug

#317 [MNOE-1260]Add abandon to cancel subscription button
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
Labels: bug

#319 [MNOE-1265] Added currency selection check in admin panel
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
Labels: bug
