Repository maestrano/mnoe-admin-panel, pull requests merged in 2018-06, with the labels that each got.

#283 [MNOE-1112] Subscription stuck in provisioning
  package.json
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/index.constants.coffee
Labels: bug

#286 [MNOE-1157] [MNOE-1158] [MNOE-1165] Expose organization current credit
  src/app/components/mnoe-api/admin/account-transactions.svc.coffee
  src/app/index.constants.coffee
  src/app/views/organization/add-transaction-modal/add-transaction-modal.controller.coffee
  src/app/views/organization/add-transaction-modal/add-transaction-modal.html
  src/app/views/organization/add-transaction-modal/add-transaction-modal.less
  src/app/views/organization/organization.controller.coffee
  src/app/views/organization/organization.html
  src/locales/en-AU.json
Labels: Status: Review Needed, enhancement

#291 [MNOE-1161] [MNOE-1131] Empty Provisioning Form
  src/app/services/provisioning-helper/provisioning-helper.coffee
  src/app/views/orders/order.controller.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
Labels: bug

#293 [MNOE-1164] Change order summary and confirm ui
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/confirm.less
  src/app/views/provisioning/order.html
  src/app/views/provisioning/order.less
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/app/views/provisioning/summary.less
  src/locales/en-AU.json
Labels: bug

#287 [MNOE-1129] Added loader while loading products
  src/app/views/settings/apps/apps.controller.coffee
  src/app/views/settings/apps/apps.html
Labels: enhancement

#295 [MNOE-1167] UI tooltip updated for item removal from cart
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/locales/en-AU.json
Labels: bug

#299 [MNOE-1172] Fix bug in subscription action flow
  src/app/views/provisioning/details.controller.coffee
  src/locales/en-AU.json
Labels: bug

#297 [MNOE-1166] add license based pricing
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/views/orders/order.html
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/order.less
  src/app/views/provisioning/product-pricing-price.coffee
  src/app/views/provisioning/product-pricing-price.html
  src/app/views/provisioning/summary.html
  src/locales/en-AU.json
Labels: bug

#305 [MNOE-1204] Update n/a tooltip icon on provisioning confirm page for UI consistency
  src/app/views/provisioning/confirm.html
Labels: bug

#294 [MNOE-1124] Unnecessary queries made from admin panel
  src/app/components/mnoe-organizations-list/mnoe-organizations-list.coffee
  src/app/components/mnoe-users-list/mno-users-list.coffee
Labels: bug

#308 [MNOE-1213] Fix staff role change confirmation
  src/app/components/mnoe-api/admin/users.svc.coffee
  src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
  src/app/views/staff/staff.controller.coffee
  src/locales/en-AU.json
Labels: bug

#307 [MNOE-1218][MNOE-1219] Product pricings & Fix typo
  src/app/views/products/product.controller.coffee
  src/app/views/provisioning/details.controller.coffee
Labels: bug

#301 Organization missing dependency
  src/app/views/organization/organization.controller.coffee
Labels: bug

#304 [MNOE-1171] Add loader when loading custom schema
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
Labels: bug
