Repository maestrano/mnoe-admin-panel, pull requests merged in 2018-05, with the labels that each got.

#255 [MNOE-1068] Display Subscription Events
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/views/orders/order.controller.coffee
Labels: Status: Review Needed, bug

#246 [OPAL-353] json schema conditional fields
  bower.json
  src/app/views/orders/order.controller.coffee
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/details.html
  src/app/views/provisioning/details.less
Labels: enhancement

#226 [MNOE-973][MNOE-888][MNOE-1011] Product Markup improvements
  src/app/components/mno-offers-list/mno-offers-list.coffee
  src/app/components/mno-offers-list/mno-offers-list.html
  src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.coffee
  src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.html
  src/app/components/mnoe-product-markups-list/mnoe-product-markups-list.less
  src/app/services/pricing-helper/pricing-helper.coffee
  src/app/views/organization/organization.controller.coffee
  src/app/views/organization/organization.html
  src/app/views/product-markups/create-markup-modal/create-markup.controller.coffee
  src/app/views/product-markups/create-markup-modal/create-markup.html
  src/app/views/product-markups/product-markups.controller.coffee
  src/locales/en-AU.json
Labels: enhancement

#258 [MNOE-1076] Expose conversion rates on Invoice screen
  src/app/views/invoices/invoice.html
  src/locales/en-AU.json
Labels: enhancement

#260 [OPAL-441] Changed category display limit from 2 to 1
  src/app/views/settings/apps/apps.controller.coffee
Labels: bug

#256 [MNOE-1065] Added pagination in update staff/clients modal
  src/app/views/staff/update-staff-clients-modal/update-staff-clients.html
Labels: bug

#266 [OPAL-420] Subscription Workflow
  src/app/components/mnoe-api/admin/products.svc.coffee
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.less
  src/app/index.route.coffee
  src/app/views/organization/organization.controller.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/details.html
  src/app/views/provisioning/layout.controller.coffee
  src/app/views/provisioning/layout.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/summary.controller.coffee
  src/locales/en-AU.json
Labels: enhancement

#253 [MNOE-970] Poll restart status to know when restart is done
  src/app/components/mnoe-api/admin/tenant.svc.coffee
  src/app/views/settings/general/general.controller.coffee
Labels: Status: In Testing, enhancement

#240 [MNOE-1020] Pagination not working
  src/app/components/mnoe-products-list/mnoe-products-list.controller.coffee
  src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
Labels: bug

#271 [OPALSUP-26] Fix locale
  src/locales/en-AU.json
Labels: bug

#269 Remove unused component
  src/app/components/mnoe-orders-list/mnoe-orders-list.coffee
  src/app/components/mnoe-orders-list/mnoe-orders-list.html
Labels: bug

#265 [MNOE-1041] Capture Organization address on UI
  src/app/components/mno-address/mno-address-input/mno-address-input.coffee
  src/app/components/mno-address/mno-address-input/mno-address-input.html
  src/app/components/mno-address/mno-address-input/mno-address-input.less
  src/app/components/mno-address/mno-address-line/mno-address-line.coffee
  src/app/components/mno-address/mno-address-line/mno-address-line.html
  src/app/components/mnoe-api/admin/organizations.svc.coffee
  src/app/index.default-config.coffee
  src/app/views/customers/create-step-1/create-step-1.controller.coffee
  src/app/views/customers/create-step-1/create-step-1.html
  src/app/views/customers/create-step-1/create-step-1.less
  src/app/views/organization/organization.html
  src/locales/en-AU.json
Labels: enhancement

#254 [MNOE-1073] Added onboarding links in products section
  src/app/components/mno-confirm/mno-confirm.html
  src/app/index.default-config.coffee
  src/app/views/products/products.controller.coffee
  src/app/views/products/products.html
  src/app/views/products/products.less
  src/locales/en-AU.json
Labels: enhancement

#270 [OPALSUP-75] Hide App selection when provisioning enabled
  src/app/views/customers/create-step-1/create-step-1.controller.coffee
  src/app/views/customers/create-step-1/create-step-1.html
Labels: bug

#264 [MNOE-1098][OPAL-429][MNOE-1113] customer request edit actions
  src/app/components/mnoe-api/admin/provisioning.svc.coffee
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.coffee
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.html
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.less
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.html
  src/app/index.route.coffee
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/order.html
  src/app/views/orders/orders.html
  src/app/views/organization/organization.html
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/details.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en-AU.json
Labels: enhancement

#262 [MNOE-1085] Added editable tax rate functionality
  src/app/views/invoices/invoice.controller.coffee
  src/app/views/invoices/invoice.html
  src/app/views/invoices/invoice.less
  src/locales/en-AU.json
Labels: enhancement

#277 [MNOE-1122] Staff can not approve/reject orders
  src/app/components/mnoe-products-list/mnoe-products-list.controller.coffee
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.coffee
  src/app/components/mnoe-subscription-events-list/mnoe-subscription-events-list.html
  src/app/components/mnoe-subscriptions-list/mnoe-subscriptions-list.coffee
  src/app/services/user-roles-helper/user-roles-helper.coffee
  src/app/views/orders/order.controller.coffee
  src/app/views/products/product.controller.coffee
  src/app/views/products/products.controller.coffee
  src/app/views/settings/apps/apps.controller.coffee
Labels: bug

#275 [MNOE-1120] Displayed all available products on new products addition
  src/app/views/settings/apps/apps.controller.coffee
Labels: bug

#280 [MNOE-1089] Subscriptions events - Capture and display the user
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/order.html
  src/app/views/orders/subscription-event-info-modal/subscription-event-info.controller.coffee
  src/app/views/orders/subscription-event-info-modal/subscription-event-info.html
  src/locales/en-AU.json
Labels: enhancement

#281 [MNOE-1117] Provisioning event sorting and filtering fix
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/orders.html
Labels: bug

#282 [MNOE-1125] Fixed Order info missing on admin panel order page
  src/app/views/orders/order.controller.coffee
  src/app/views/orders/order.html
  src/app/views/orders/orders.html
  src/locales/en-AU.json
Labels: bug

#284 [MNOE-1137] Company Cart System: Issue with Modifying subscription within the cart
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/locales/en-AU.json
Labels: bug
